carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name="remove_cart_item"),
    path('checkout/',views.checkout,name="checkout"),
    path('cancel_order/<id>/',views.cancel_order,name="cancel_order"),
    # path('decreasequantity/',views.decreaseQuantity,name="decreaseQuantity"),
    # path('increase_quantity/',views.increaseQuantity,name="increaseQuantity"),

]

orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('place_order',views.place_order,name='place_order'),
    path('payments/',views.payments,name='payments'),
    path('payment_status/',views.payment_status,name='payment_status'),
    path('payment/',views.payment,name='payment'),
    path('cod/',views.cod,name='cod'),
    path('order_complete/',views.order_complete,name='order_complete'),
    path('my_orders',views.my_orders,name="my_orders"),
    path('couponremove/',views.couponremove,name='couponremove'),
    
]

zapiens_cart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('store/',include('store.urls')),
    path('carts/',include('carts.urls')),
    path('accounts/',include('accounts.urls')),
    path('admins/',include('admins.urls')),
    path('orders/',include('orders.urls')),
    path('wishlist/',include('wishlists.urls'))
    

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.db import models
from django.db import models
from accounts.models import Account
from store.models import Product,Variation


# Create your models here.
class Payment(models.Model):
    user            =   models.ForeignKey(Account,on_delete=models.CASCADE)
    payment_id      =   models.CharField(max_length=100)
    payment_method  =   models.CharField(max_length=100)
    amount_paid     =   models.CharField(max_length=100)
    status          =   models.CharField(max_length=100)
    created_at      =   models.DateTimeField(auto_now_add=True)
    order_id        =   models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.payment_id

class Order(models.Model):
    STATUS = (
        ('New' ,'New' ),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
        ('out for Delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered'),
    )
    user            =      models.ForeignKey(Account,on_delete=models.SET_NULL,null=True)
    payment         =      models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    order_number    =      models.CharField(max_length=100)
    first_name      =      models.CharField(max_length=50)
    last_name       =      models.CharField(max_length=50)
    phone           =      models.CharField(max_length=15)
    email           =      models.EmailField(max_length=50)
    address_line_1  =      models.CharField(max_length=100)
    address_line_2  =      models.CharField(max_length=100,blank=True)
    country         =      models.CharField(max_length=50,blank=True,null=True)
    state           =      models.CharField(max_length=50)
    city            =      models.CharField(max_length=50)
    pincode         =      models.CharField(max_length=50)
    order_total     =      models.FloatField()
    tax             =      models.FloatField()
    status          =      models.CharField(max_length=50,choices=STATUS,default='New')
    ip              =      models.CharField(blank=True,max_length=20)
    is_ordered      =      models.BooleanField(default=False)
    created_at      =      models.DateTimeField(auto_now_add=True)
    updated_at      =      models.DateTimeField(auto_now=True)

    def full_name(self):
        return f"{self.first_name }{self.last_name}"
    
    def full_address(self):
        return f"{self.address_line_1 } { self.address_line_2}"



    def __str__(self):
        return self.first_name

class OrderProduct(models.Model):
    STATUS = (
        ('New' ,'New' ),
        ('Accepted', 'Accepted'),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
        ('Failed', 'Failed'),
        ('Delivered', 'Delivered'),
    )
    
    order           =   models.ForeignKey(Order,on_delete=models.CASCADE)
    payment         =   models.ForeignKey(Payment,on_delete=models.SET_NULL,blank=True,null=True)
    user            =   models.ForeignKey(Account,on_delete=models.CASCADE)
    product         =   models.ForeignKey(Product,on_delete=models.CASCADE)
    variations      =   models.ManyToManyField(Variation,blank=True)
    quantity        =   models.IntegerField()
    product_price   =   models.FloatField()
    ordered         =   models.BooleanField(default=False)
    created_at      =   models.DateTimeField(auto_now_add=True)
    updated_at      =   models.DateTimeField(auto_now=True)
    status          =   models.CharField(max_length=50,choices=STATUS,default='New')

    def __str__(self):
        return self.product.product_name
class Coupons(models.Model):
    coupon_name = models.CharField(max_length=250)
    coupon_code = models.CharField(max_length=50)
    coupon_offer = models.IntegerField()
    coupon_min = models.IntegerField()
    coupon_start = models.DateTimeField(default=None)
    coupon_end = models.DateTimeField(default=None)

accounts/forms.py
from pyexpat import model
from django import forms
from .models import Account, UserProfile


class RegistrationForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        'PlaceHolder':'Enter Password'
    }))
    confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={
        'PlaceHolder':'Confirm Password'
    }))    
    class Meta:
        model=Account
        fields=['first_name','last_name','phone_number','email','password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password=self.cleaned_data.get("password")
        confirm_password=self.cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Passwords do not match"
            )

        if len(password)<8:
            raise forms.ValidationError(
                "Password should Contain minimum of 8 characters!"
            )

        phone_number = cleaned_data.get('phone_number')
        if len(phone_number) != 10:
            raise forms.ValidationError(
                "Enter a valid Phone number"
            )  

    def __init__(self,*args, **kwargs):
        super(RegistrationForm,self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder']='First Name'
        self.fields['last_name'].widget.attrs['placeholder']='Last Name'
        self.fields['phone_number'].widget.attrs['placeholder']='Phone Number'
        self.fields['email'].widget.attrs['placeholder']='Email Address'


        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'


class VerifyForm(forms.Form):
    code = forms.CharField(max_length=8, required=True, help_text='')

class otploginForm(forms.Form):
    phone_number=forms.CharField(max_length=13,required=True,help_text='')
class VerifyotpForm(forms.Form):
    code = forms.CharField(max_length=8, required=True, help_text='')

class UserForm(forms.ModelForm):
    class Meta:
        model=Account
        fields=['first_name','last_name','phone_number']
    def __init__(self,*args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'

class UserProfileForm(forms.ModelForm):
    class Meta:
        model   =   UserProfile
        fields = ['address_line_1','address_line_2','city','state','country','pincode']
    def __init__(self,*args, **kwargs):
        super(UserProfileForm,self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model   =   Order
        fields  =   [
            'first_name','last_name','phone','email','address_line_1','address_line_2','country','state','city','pincode'
        ]

templates/orders/add_address.html
{% extends 'base.html' %}

{% block content %}

{% include "includes/alerts.html" %}
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
            <aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item " href="/accounts/dashboard/"> Dashboard </a>
        <a class="list-group-item " href="/orders/my_orders"> My Orders </a>
        <a class="list-group-item " href="/accounts/add_address"> Add Address </a>
        <a class="list-group-item active" href="/accounts/edit_profile/"> Edit Profile </a>
        <a class="list-group-item " href="/accounts/change_password/">Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block " href="#"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3 ">Add Address</strong>

            </header>
            
                 <div class="col-md-12">
                     <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6 ">
                                <label>First Name</label>
                                <input type="text" name="first_name"  maxlength="50" class="form-control" required="" id="id_first_name">
                            </div>
                            <div class="form-group col-md-6 ">
                                <label>Last Name</label>
                                <input type="text" name="last_name"  maxlength="50" class="form-control" required="" id="id_last_name">
                             </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6 ">
                                <label>Phone Number</label>
                                <input type="text" name="phone_number"  maxlength="10" class="form-control" required="" id="id_phone_number">
                            </div>
                            
                        </div>
                        <div class="form-group">
                                <label>Address Line 1</label>
                                <input type="text" name="address_line_1"  maxlength="100" class="form-control" id="id_address_line_1">
                            </div>
                        <div class="form-group">
                                <label>Address Line 2</label>
                                <input type="text" name="address_line_2"  maxlength="100" class="form-control" id="id_address_line_2">
                             </div>
                        <div class="form-row">
                            <div class="form-group col-md-3 ">
                                <label>City</label>
                                <input type="text" name="city"  maxlength="20" class="form-control" id="id_city">
                            </div>
                            <div class="form-group col-md-3 ">
                                <label>State</label>
                                <input type="text" name="state"  maxlength="20" class="form-control" id="id_state">
                            </div>
                            <div class="form-group col-md-3 ">
                                <label>Country</label>
                                <input type="text" name="country"  maxlength="20" class="form-control" id="id_country">
                             </div>
                            <div class="form-group col-md-3 ">
                                <label>Pincode</label>
                                <input type="text" name="pincode"  maxlength="20" class="form-control" id="id_pincode">
                            </div>
                        </div>
                        <input type="submit" value="Save" class="btn btn-primary mb-2">
                        
                     </form>

                 </div>
                </article></main></div>
            </div> <!-- card-body .// -->



             <!-- order-group.// -->
        
     <!-- row.// -->
    


    </section>

{% endblock content %}

templates/orders/base.html
{% extends 'base.html' %}
{% load static %}

<html>
<body>
    <link rel="icon" type="image/png" href="{% static 'image/logo.png' %}"/>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/df00c4319e.js" crossorigin="anonymous"></script>

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">


    {% block content %}


    {% endblock %}


<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/orders/cod.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 mt-5 "> 
        
            {% if messages %} 
                <div class="col-lg-12">

                    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
                       
                        {% for message in messages %}
                        {{ message }}
                        {% endfor %}
                       
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                </div> {% endif %}
            <div class="checkout__order">
                <h5>Your order</h5>
                <div class="checkout__order__product">
                    <ul>
                        <li class="list-group-item list-group-item-primary>
                            <span class="top__text">Product</span>
                            <span class="top__text__right">Total</span>
                        </li>{% for item in cart_items %}
                        <li class=list-group-item list-group-item-primary>{{item.product.product_name}} x {{item.quantity}}=<span>₹ {{ item.sub_total }}</span></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="checkout__order__total">
                    <ul>
                        <!-- <li>Subtotal <span>₹ {{total}}</span></li>
                        <li>Tax <span>₹ {{tax}}</span></li> -->
                        <li class="list-group-item list-group-item-primary">Amount to Pay <span>₹ {{grand_total}}</span></li>
                    </ul>
                </div>

                <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit"  class="btn btn-primary ">Place Order</button>
                </form>

              
           
            </div>
        </div>
        </div> 
       


    </div>


</div>

{% endblock %}

templates/orders/order_complete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src="{% static '/images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{order.full_name}}</li>
                                    <li>{{order.full_address}}</li>
                                    <li>{{order.city}}, {{order.state}}</li>
                                    <li>{{order.country}}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #{{order_number}}</li>
                                        <li><strong>Transaction ID</strong> {{transID}}</li>
                                        <li><strong>Order Date:</strong> {{order.created_at}}</li>
                                        <li><strong>Status:</strong> {{payment.status}}</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Products</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                          {% for item in ordered_products %}
                                            <tr>
                                                <td>{{item.product.product_name}}
                                                  <p class="text-muted small">
                                          					{% if item.variations.all %}
                                          						{% for i in item.variations.all %}
                                          							{{ i.variation_category | capfirst }} : {{ i.variation_value | capfirst }} <br>
                                          						{% endfor %}
                                          					{% endif %}
                                          				</p>
                                                </td>
                                                <td class="text-center">{{item.quantity}}</td>
                                                <td class="text-center">₹{{item.product_price}} INR</td>
                                            </tr>
                                          {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">₹{{subtotal}} INR</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">₹{{order.tax}} INR</th>
                                            </tr>

                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">₹{{subtotal}} INR</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>


{% endblock %}

templates/orders/order_recieved_email.html
{% autoescape off %}


Hi {{user.first_name}},

YOUR ORDER HAS BEEN PLACED!

Order Number:{{order.order_number}}
Keep this for future reference
{% endautoescape %}

templates/orders/payments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
 
    <div class="row">
        <aside class="col-lg-8">
            <div class="card">
                <h5 class="card-header">Billing Address</h5>
                <div class="card-body">
                  <p class="card-text mb-0">{{order.full_name}}</p>
                  <p class="card-text mb-0">{{order.full_address}}</p>
                  <p class="card-text mb-0">{{order.city}},{{order.state}}</p>
                  <p class="card-text mb-0">{{order.country}}</p>
                  <p class="card-text mb-0">{{order.phone}}</p>
                  <p class="card-text mb-0">{{order.email}}</p>

                </div>
              </div>
              <div class="card">
                <h5 class="card-header">Product Preview</h5>
                <div class="card-body">
                  <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                      <th scope="col" class="text-right" width="200"> </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% for cart_item in cart_items %}
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                                <figcaption class="info">
                                    <a href="{{cart_item.product.get_url}}" class="title text-dark" >{{cart_item.product.product_name}}</a>
                                        
                                        <p  class="text-muted small">{% if cart_item.variations.all %}
                                                {% for item in cart_item.variations.all %}
                                                    {{ item.variation_category| capfirst }} : {{ item.variation_value | capfirst }} <br>
                                                {% endfor %}
                                            {% endif %}</p>
                                </figcaption>
                            </figure>
                        </td>
                        <td> 
                            <!-- col.// -->
                            <div class="price-wrap"> 
                                <var class="price">{{cart_item.quantity}}</var> 
                                
                            </div> 
                                    <!-- col.// -->
                        </td>
                        <td> 
                            <div class="price-wrap"> 
                                <var class="price">₹{{cart_item.sub_total}}</var> 
                                <small class="text-muted"> ₹{{cart_item.product.price}} each </small> 
                            </div> <!-- price-wrap .// -->
                        </td>
                        
                    </tr>
                    {% endfor %}
                    
                    </tbody>
                    </table>
                </div>
              </div>
    
        </aside> <!-- col.// -->
        <aside class="col-lg-4">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">₹{{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ₹{{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Grand Total:</dt>
                  <dd class="text-right text-dark b"><strong>₹{{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'cod' %}" class="btn btn-primary btn-block mb-3">Cash On Delivery</a>
                <a id="rzp-button1" href=" {% url 'payment' %}"
                                class="btn btn-success btn-order btn-block mb-3">Razorpay</a>
                <div id="paypal-button-container">
                  {% comment %} paypal Button  {% endcomment %}
                 
                </div>
                
                

            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
  
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>

    <script>

      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    
      var amount = "{{ grand_total }}"
      var url = "{% url 'payments' %}"
      var csrftoken = getCookie('csrftoken');
      var orderID = "{{order.order_number}}"
      var payment_method = 'PayPal'
      var redirect_url = "{% url 'order_complete' %}"
      // Render the PayPal button into #paypal-button-container
      paypal.Buttons({
    
        style: {
          color: 'blue',
          shape: 'rect',
          label: 'pay',
          height: 40
        },
    
        // Set up the transaction
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: amount,
              }
            }]
          });
        },
    
        // Finalize the transaction
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            // Show a success message to the buyer
            console.log(details);
            sendData();
            function sendData(){
              fetch(url, {
                method : "POST",
                headers: {
                  "Content-type": "application/json",
                  "X-CSRFToken": csrftoken,
                },
                body: JSON.stringify({
                  orderID: orderID,
                  transID: details.id,
                  payment_method: payment_method,
                  status: details.status,
                }),
              })
              .then((response) => response.json())
              .then((data) => {
                window.location.href = redirect_url + '?order_number='+data.order_number+'&payment_id='+data.transID;
              });
            }
          });
        }
    
    
      }).render('#paypal-button-container');

    </script>




    




{% endblock content %}